"""'orgin_url'

Revision ID: 230e90f5c618
Revises: 58f48b30bbb6
Create Date: 2018-05-30 15:16:18.693497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230e90f5c618'
down_revision = '58f48b30bbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_category', sa.Column('origin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_category', 'origin_url')
    # ### end Alembic commands ###
